### PR TITLE
Change to session bus for miner

### LINKED ISSUE #93: Can't find org.bluez with new setup - possibly because running in venv
```
root@nebra-d06a21:/opt# ./start-gateway-config.sh 
^C
2021-09-14 02:53:03;DEBUG;Starting with the following ENV:
        SENTRY_DSN=https://3234e2c67fe04c3e9f8b0c9b118c415a@o571444.ingest.sentry.io/5725518
        BALENA_APP_NAME=HELIUM-LIGHT-TEST
        BALENA_DEVICE_UUID=28c44310bfc8ffc6098bce2b3696336e
        VARIANT=NEBHNT-IN1
        ETH0_MAC_ADDRESS_FILEPATH=/sys/class/net/eth0/address
        WLAN0_MAC_ADDRESS_FILEPATH=/sys/class/net/wlan0/address
        MINER_KEYS_FILEPATH=/var/data/public_keys
        DIAGNOSTICS_JSON_URL=http://localhost:80?json=true
        ETHERNET_IS_ONLINE_FILEPATH=/sys/class/net/eth0/carrier
        FIRMWARE_VERSION=2021.09.09.0

2021-09-14 02:53:03;DEBUG;Read eth0 mac address DC:A6:32:D1:47:D6 and wlan0 42:47:6A:28:96:10
2021-09-14 02:53:03;DEBUG;Read onboarding pub_key: 11xcYBAeqhYfRznipZRvqaRF8H9jwVnTVftPDsAfLL7gJDK2hD9 + animal_name: suave-heather-hare
Traceback (most recent call last):
  File "/opt/venv/lib/python3.7/site-packages/dbus/bus.py", line 177, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/opt/venv/lib/python3.7/site-packages/dbus/bus.py", line 363, in get_name_owner
    's', (bus_name,), **keywords)
  File "/opt/venv/lib/python3.7/site-packages/dbus/connection.py", line 653, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.bluez': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "gatewayconfig/__main__.py", line 49, in <module>
    main()
  File "gatewayconfig/__main__.py", line 20, in main
    start()
  File "gatewayconfig/__main__.py", line 40, in start
    ETH0_MAC_ADDRESS_FILEPATH, WLAN0_MAC_ADDRESS_FILEPATH, MINER_KEYS_FILEPATH, DIAGNOSTICS_JSON_URL, ETHERNET_IS_ONLINE_FILEPATH, FIRMWARE_VERSION)
  File "/opt/gatewayconfig/gatewayconfig_app.py", line 42, in __init__
    self.bluetooth_services_processor = BluetoothServicesProcessor(eth0_mac_address, wlan0_mac_address, onboarding_key, pub_key, firmware_version, ethernet_is_online_filepath, self.shared_state)
  File "/opt/gatewayconfig/processors/bluetooth_services_processor.py", line 11, in __init__
    self.register()
  File "/opt/lib/cputemp/service.py", line 94, in register
    adapter = BleTools.find_adapter(self.bus)
  File "/opt/lib/cputemp/bletools.py", line 44, in find_adapter
    "/"),
  File "/opt/venv/lib/python3.7/site-packages/dbus/bus.py", line 243, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/opt/venv/lib/python3.7/site-packages/dbus/proxies.py", line 250, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/opt/venv/lib/python3.7/site-packages/dbus/bus.py", line 182, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/opt/venv/lib/python3.7/site-packages/dbus/bus.py", line 280, in start_service_by_name
    'su', (bus_name, flags)))
  File "/opt/venv/lib/python3.7/site-packages/dbus/connection.py", line 653, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.bluez was not provided by any .service files
Sentry is attempting to send 1 pending error messages
Waiting up to 2 seconds
Press Ctrl-C to quit
```

### LINKED ISSUE #94: Errors with dbus container (tracking issue)
system d error

```
root@nebra-d06a21:/opt# ./start-gateway-config.sh 
method return time=1631647401.996775 sender=org.freedesktop.DBus -> destination=:1.1760 serial=3 reply_serial=2
   array [
      string "org.freedesktop.DBus"
      string "com.helium.Miner"
      string ":1.812"
      string ":1.1"
      string ":1.1760"
      string ":1.2"
   ]
DBus is now accepting connections
Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.systemd1 was not provided by any .service files

Error when running `./systemd-stop-unit.sh bluetooth.service`
```
dbus[1926]: arguments to dbus_message_new_method_call() were incorrect, assertion "_dbus_check_is_valid_path (path)" failed in file ../../../dbus/dbus-message.c line 1366.
This is normally a bug in some application using the D-Bus library.

  D-Bus not built with -rdynamic so unable to print a backtrace
dbus[1930]: arguments to dbus_message_new_method_call() were incorrect, assertion "_dbus_check_is_valid_path (path)" failed in file ../../../dbus/dbus-message.c line 1366.
This is normally a bug in some application using the D-Bus library.

  D-Bus not built with -rdynamic so unable to print a backtrace
dbus[1934]: arguments to dbus_message_new_method_call() were incorrect, assertion "_dbus_check_is_valid_path (path)" failed in file ../../../dbus/dbus-message.c line 1366.
This is normally a bug in some application using the D-Bus library.

  D-Bus not built with -rdynamic so unable to print a backtrace
dbus[1938]: arguments to dbus_message_new_method_call() were incorrect, assertion "_dbus_check_is_valid_path (path)" failed in file ../../../dbus/dbus-message.c line 1366.
This is normally a bug in some application using the D-Bus library.
```

bluetoothd error

```
root@nebra-d06a21:/opt# source dbus-wait.sh && wait_for_dbus && /usr/lib/bluetooth/bluetoothd  --nodetach
method return time=1631647717.013524 sender=org.freedesktop.DBus -> destination=:1.2647 serial=3 reply_serial=2
   array [
      string "org.freedesktop.DBus"
      string "com.helium.Miner"
      string ":1.2647"
      string ":1.812"
      string ":1.1"
      string ":1.2"
   ]
DBus is now accepting connections
bluetoothd[3705]: Bluetooth daemon 5.50
bluetoothd[3705]: Starting SDP server
bluetoothd[3705]: binding L2CAP socket: Address already in use
bluetoothd[3705]: Server initialization failed
bluetoothd[3705]: Bluetooth management interface 1.14 initialized
bluetoothd[3705]: Failed to start listening: l2cap_bind: Address already in use (98)
bluetoothd[3705]: Failed to create GATT database for adapter
bluetoothd[3705]: Unable to register new adapter
cannot exec in a stopped state: unknown
SSH session disconnected
SSH reconnecting...
Spawning shell...
```

### PR DESCRIPTION
**Pull request by shawaj**
**Why**

Remove the need for custom device types to enable miner to listen on com.helium.Miner over dbus

**How**

Change to session bus for miner.

Leaves Bluetooth using system bus

**References**

Closes #93
Closes #94

### CODE REVIEW

File: dbus-wait.sh [hunk 1]
```diff
@@ -0,0 +1,19 @@
+#!/usr/bin/env sh
+
+wait_for_dbus() {
```
Comment (marvinmarnold) [inline dbus-wait.sh:3]: I can't think of a clean way to remove code duplication between this and [hm-diag](https://github.com/NebraLtd/hm-diag/pull/149/files#diff-a84b061bc6245cd09854d50b5257a6e60418bbdc76ec91788faae259588be97dR5) without a lot of overtooling. Eventually creating a APT release similar to hm-pyhelper is one long term thought but def overkill now.

**Review by marvinmarnold — APPROVED** [review]

File: dbus-wait.sh (hunk 1 above)
Comment (shawaj) [reply dbus-wait.sh:3]: It's also in hm-miner as well just FYI but yeah couldn't think of an easy way to remove duplicate

Comment (shawaj) [reply dbus-wait.sh:3]: Having said that, the one in hm-miner checks the system bus instead of the session bus
